version: "3.8"

services:
  postgres:
    image: postgres:16.2
    container_name: htmx-demo-db
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=htmx-demo-db
    ports:
      - '5432:5432'

  server:
    container_name: htmx-demo-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/htmx-demo-db
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres
